### ISSUE TITLE
DDR build fails with LOG=debug: closed/DDR.gmk:189: *** empty variable name. Stop.

### ISSUE THREAD

**Issue by Hello71** [ibmruntimes/openj9-openjdk-jdk14#72]
```
/tmp/portage/dev-java/openjdk-openj9-14.0.2.0.21.0/work/openj9-openjdk-jdk14-96c908f820cb6179aaafb4306256a6d53417e755/closed/DDR.gmk:189: *** empty variable name.  Stop.
```

not 100% sure this is caused by LOG=debug, but most likely. see [JDK-8215213](https://bugs.openjdk.java.net/browse/JDK-8215213)

**Comment by pshipton** [comment]
JDK14 is obsolete. If there is still an issue with OpenJ9 builds, pls open it in https://github.com/eclipse/openj9/issues
